CREATE TABLE CRITERE (
		CODECRITERE VARCHAR(16) NOT NULL,
		PROFILCRITERE VARCHAR(16) NOT NULL,
		LIBELLECRITERE VARCHAR(32),
		SORTORDERCRITERE INTEGER,
		CLASSEMENT BIGINT,
		PLACEMENT BIGINT,
		CODEFFTA VARCHAR(3),
		PRIMARY KEY (CODECRITERE, PROFILCRITERE)
	);

CREATE TABLE ENTITE (
		AGREMENTENTITE VARCHAR(7) NOT NULL,
		NOMENTITE VARCHAR(64),
		ADRESSEENTITE BIGINT,
		CODEPOSTALENTITE VARCHAR(5),
		VILLEENTITE VARCHAR(64),
		NOTEENTITE BIGINT,
		TYPEENTITE INTEGER,
		PRIMARY KEY (AGREMENTENTITE)
	);

CREATE TABLE ARCHERSFFTA (
		NUMLICENCEARCHER VARCHAR(64) NOT NULL,
		NOMARCHER VARCHAR(64),
		PRENOMARCHER VARCHAR(64),
		ALIASARCHER VARCHAR(128),
		CLUBARCHER VARCHAR(64),
		ARCARCHER INTEGER,
		CATEGORIEARCHER INTEGER,
		GENREARCHER INTEGER,
		NIVEAUARCHER CHAR(1),
		LIBELLENIVEAU VARCHAR(1),
		LIBELLECATEGORIE VARCHAR(8),
		AGREMENTCLUBARCHER VARCHAR(7),
		DATENAISS VARCHAR(8),
		CERTIFMEDICAL INTEGER,
		INC2 INTEGER,
		PRIMARY KEY (NUMLICENCEARCHER)
	);

CREATE TABLE DISTINGUER (
		NUMLICENCEARCHER VARCHAR(7) NOT NULL,
		CODECRITEREELEMENT VARCHAR(16) NOT NULL,
		CODECRITERE VARCHAR(16) NOT NULL,
		PROFILCRITERE VARCHAR(16) NOT NULL,
		PRIMARY KEY (NUMLICENCEARCHER, CODECRITEREELEMENT, CODECRITERE, PROFILCRITERE)
	);

CREATE TABLE ENTITEFFTA (
		NUMENTITE INTEGER NOT NULL,
		AGREMENTENTITE VARCHAR(7),
		NOMENTITE VARCHAR(64),
		VILLEENTITE VARCHAR(64),
		LIGUEENTITE VARCHAR(2),
		CDENTITE VARCHAR(9),
		PRIMARY KEY (NUMENTITE)
	);

CREATE TABLE CRITEREELEMENT (
		CODECRITEREELEMENT VARCHAR(16) NOT NULL,
		CODECRITERE VARCHAR(16) NOT NULL,
		PROFILCRITERE VARCHAR(16) NOT NULL,
		LIBELLECRITEREELEMENT VARCHAR(32),
		ACTIF BIGINT,
		PRIMARY KEY (CODECRITEREELEMENT, CODECRITERE, PROFILCRITERE)
	);

CREATE TABLE ARCHERS (
		NUMLICENCEARCHER VARCHAR(7) NOT NULL,
		NOMARCHER VARCHAR(64),
		PRENOMARCHER VARCHAR(64),
		CERTIFMEDICAL BIGINT,
		AGREMENTENTITE VARCHAR(7),
		GENREFFTA INTEGER,
		CATEGORIEFFTA INTEGER,
		NIVEAUFFTA INTEGER,
		ARCFFTA INTEGER,
		PRIMARY KEY (NUMLICENCEARCHER)
	);

CREATE INDEX I_NOM_ARCHERS ON ARCHERS (NOMARCHER ASC);