-- @author Aurélien JEOFFRAY
-- Code HSQLDB A décommenter si utilisation de HSQLDB à la place de H2
-- SET TABLE EntiteFFTA SOURCE "FICLUB.TXT;fs=\semi";
-- SET TABLE ArchersFFTA SOURCE "Licence.TXT;fs=\semi";-- fin code HSQLDB

-- DELETE FROM Entite;
-- DELETE FROM Archers;

-- Code H2 A commenter si utilisation de HSQLDB
-- Integration du fichier ASCII
SET MULTI_THREADED 1;

TRUNCATE TABLE EntiteFFTA;
INSERT INTO EntiteFFTA SELECT distinct NUM,AGR,NOM,
	VILLE,LIGUE,CD from CSVREAD('base/FICLUB.TXT','NUM;AGR;NOM;VILLE;LIGUE;CD;INC1;INC2;INC3;INC4',null,';');

TRUNCATE TABLE ArchersFFTA;
INSERT INTO ArchersFFTA (NOMARCHER,NUMLICENCEARCHER,PRENOMARCHER,
	ALIASARCHER,CLUBARCHER,ARCARCHER,CATEGORIEARCHER,GENREARCHER,NIVEAUARCHER,
	LIBELLENIVEAU,LIBELLECATEGORIE,AGREMENTCLUBARCHER,DATENAISS,CERTIFMEDICAL,
	INC2) SELECT distinct * from CSVREAD('base/Licence.TXT','NOMARCHER;NUMLICENCEARCHER;PRENOMARCHER;ALIASARCHER;CLUBARCHER;ARCARCHER;CATEGORIEARCHER;GENREARCHER;NIVEAUARCHER;LIBELLENIVEAU;LIBELLECATEGORIE;AGREMENTCLUBARCHER;DATENAISS;CERTIFMEDICAL;INC2',null,';');
-- Fin code H2

-- Code Commun
MERGE INTO Entite (AGREMENTENTITE, NOMENTITE, VILLEENTITE) 
	SELECT AGREMENTENTITE, NOMENTITE, VILLEENTITE FROM EntiteFFTA
		WHERE NomEntite <> 'DEPARTEMENT FEDERATION';

MERGE INTO Archers (NUMLICENCEARCHER, NOMARCHER, PRENOMARCHER, 
	CERTIFMEDICAL, AGREMENTENTITE, GENREFFTA, CATEGORIEFFTA, NIVEAUFFTA,
	ARCFFTA) SELECT NUMLICENCEARCHER, NOMARCHER, PRENOMARCHER, 
		CERTIFMEDICAL, AGREMENTCLUBARCHER, GENREARCHER-1, 
		CATEGORIEARCHER-1,NIVEAUARCHER, ARCARCHER-1 FROM ArchersFFTA;
-- Fin code Commun

-- Code HSQLDB
-- SET TABLE EntiteFFTA SOURCE "";
-- SET TABLE ArchersFFTA SOURCE "";
-- Fin HSQLDB

-- Code H2
TRUNCATE TABLE EntiteFFTA;
TRUNCATE TABLE ArchersFFTA;
-- Fin code H2

COMMIT;
