-- @author Aurélien JEOFFRAY
SET MULTI_THREADED 1;
SET LOG 0;

SET @DATE_MODIF = CURRENT_DATE();
CREATE SCHEMA IF NOT EXISTS IMPORTFFTA;

CREATE TEMPORARY TABLE IMPORTFFTA.RESULT_CLUB AS SELECT * FROM CSVREAD('ressources/update/result_club.txt',null,'ISO-8859-15',STRINGDECODE('\t'));
MERGE INTO Entite (AGREMENTENTITE, NOMENTITE, VILLEENTITE, TYPEENTITE, DATEMODIF) 
    SELECT distinct "Agrément","Désignation","Localité",3, @DATE_MODIF
        from IMPORTFFTA.RESULT_CLUB
        where "Désignation" <> 'DEPARTEMENT FEDERATION';
        
DELETE FROM Entite WHERE DATEMODIF <> @DATE_MODIF;

UPDATE ENTITE SET TYPEENTITE = 2 WHERE AGREMENTENTITE like '%000';
UPDATE ENTITE SET TYPEENTITE = 1 WHERE AGREMENTENTITE like '%00000';
UPDATE ENTITE SET TYPEENTITE = 0 WHERE AGREMENTENTITE like '0000000';

DROP SCHEMA IMPORTFFTA;

COMMIT;

SET LOG 1;