-- @author Aurélien JEOFFRAY
-- Optimise les performances sur les machines multi processeur/core ou Hyper-Threading
SET MULTI_THREADED 1;

-- Integration des fichiers ASCII
TRUNCATE TABLE EntiteFFTA;
INSERT INTO EntiteFFTA SELECT distinct NUM,AGR,NOM,
	VILLE,LIGUE,CD from CSVREAD('{temp}/FICLUB.TXT','NUM;AGR;NOM;VILLE;LIGUE;CD;INC1;INC2;INC3;INC4',null,';');

TRUNCATE TABLE ArchersFFTA;
INSERT INTO ArchersFFTA (NOMARCHER,NUMLICENCEARCHER,PRENOMARCHER,
	ALIASARCHER,CLUBARCHER,ARCARCHER,CATEGORIEARCHER,GENREARCHER,NIVEAUARCHER,
	LIBELLENIVEAU,LIBELLECATEGORIE,AGREMENTCLUBARCHER,DATENAISS,CERTIFMEDICAL,
	INC2) SELECT distinct * from CSVREAD('{temp}/Licence.TXT','NOMARCHER;NUMLICENCEARCHER;PRENOMARCHER;ALIASARCHER;CLUBARCHER;ARCARCHER;CATEGORIEARCHER;GENREARCHER;NIVEAUARCHER;LIBELLENIVEAU;LIBELLECATEGORIE;AGREMENTCLUBARCHER;DATENAISS;CERTIFMEDICAL;INC2',null,';');

-- Placement/Mise à jour des données dans leurs table définitive
MERGE INTO Entite (AGREMENTENTITE, NOMENTITE, VILLEENTITE) 
	SELECT AGREMENTENTITE, NOMENTITE, VILLEENTITE FROM EntiteFFTA
		WHERE NomEntite <> 'DEPARTEMENT FEDERATION';

MERGE INTO Archers (NUMLICENCEARCHER, NOMARCHER, PRENOMARCHER, 
	CERTIFMEDICAL, AGREMENTENTITE, GENREFFTA, CATEGORIEFFTA, NIVEAUFFTA,
	ARCFFTA) SELECT NUMLICENCEARCHER, NOMARCHER, PRENOMARCHER, 
		CERTIFMEDICAL, AGREMENTCLUBARCHER, GENREARCHER-1, 
		CATEGORIEARCHER-1,NIVEAUARCHER, ARCARCHER-1 FROM ArchersFFTA;

-- Nettoyage des tables
-- DELETE FROM Entite WHERE AGREMENTENTITE NOT IN (SELECT AGREMENTENTITE FROM EntiteFFTA);
DELETE FROM Archers WHERE NUMLICENCEARCHER NOT IN (SELECT NUMLICENCEARCHER FROM ArchersFFTA);

-- Vidage des tables temporaires
TRUNCATE TABLE EntiteFFTA;
TRUNCATE TABLE ArchersFFTA;

COMMIT;
