-- @author Aurélien JEOFFRAY
SET MULTI_THREADED 1;
SET LOG 0;

SET @DATE_MODIF = CURRENT_DATE();

MERGE INTO VILLE (INSEE,NOM,ALTITUDE,LONGITUDE_RADIAN,LATITUDE_RADIAN,POP99,SURFACE,PAYS) SELECT INSEE,NOM,ALTITUDE,LONGITUDE_RADIAN,LATITUDE_RADIAN,POP99,SURFACE,'fr' as PAYS FROM CSVREAD('ressources/update/villes_fr.csv',null,'ISO-8859-15',STRINGDECODE(';'));

COMMIT;

SET LOG 1;