-- @author Aurélien JEOFFRAY
-- Optimise les performances sur les machines multi processeur/core ou Hyper-Threading
SET MULTI_THREADED 1;
SET LOG 0;

SET @DATE_MODIF = CURRENT_DATE();
CREATE SCHEMA IF NOT EXISTS IMPORTFFTA;

-- Integration des fichiers ASCII
CREATE TEMPORARY TABLE IMPORTFFTA.RESULT_CLUB AS SELECT * FROM CSVREAD('{temp}/result_club.txt',null,'ISO-8859-15',STRINGDECODE('\t'));
MERGE INTO Entite (AGREMENTENTITE, NOMENTITE, VILLEENTITE, TYPEENTITE, DATEMODIF) 
    SELECT distinct "Agrément","Désignation","Localité",3, @DATE_MODIF
        from IMPORTFFTA.RESULT_CLUB
        where "Désignation" <> 'DEPARTEMENT FEDERATION';

CREATE TEMPORARY TABLE IMPORTFFTA.RESULT_LICENCE AS SELECT * FROM CSVREAD('{temp}/result_licence.txt',null,'ISO-8859-15',STRINGDECODE('\t'));
CREATE TEMPORARY TABLE IMPORTFFTA.FFTACATEGORIE (NUM INTEGER PRIMARY KEY, CODE VARCHAR(2));
INSERT INTO IMPORTFFTA.FFTACATEGORIE VALUES (0,'P'), (1,'B'), (2,'M'), (3,'C'), (4,'J'), (5,'S'), (6,'V'), (7,'SV');
CREATE TEMPORARY TABLE IMPORTFFTA.FFTAARC (NUM INTEGER PRIMARY KEY, CODE VARCHAR(2));
INSERT INTO IMPORTFFTA.FFTAARC VALUES (0,'CL'), (1,'CO'), (2,'AD'), (3,'AC'), (4,'BB'), (5,'TL');
CREATE TEMPORARY TABLE IMPORTFFTA.FFTANIVEAU (NUM INTEGER PRIMARY KEY, CODE VARCHAR(2));
INSERT INTO IMPORTFFTA.FFTANIVEAU VALUES (0,'0'), (1,'1'), (2,'2'), (3,'3'), (4,'P'), (5,'Z');
MERGE INTO Archers (NUMLICENCEARCHER, NOMARCHER, PRENOMARCHER, 
    CERTIFMEDICAL, AGREMENTENTITE, SEXE, DATENAISS, CATEGORIE, NIVEAU,
    ARC, DATEMODIF) SELECT "N° Adh", "Nom", "Prénom", 
        CASEWHEN("Certificat" is not NULL, TRUE, FALSE), "Agrément", CASEWHEN("Sexe"='H', 0, 1), 
        PARSEDATETIME("Naissance",'yyyyMMdd'),
        (select NUM FROM IMPORTFFTA.FFTACATEGORIE where CODE="Catégorie"),
        IFNULL((select NUM FROM IMPORTFFTA.FFTANIVEAU where CODE="Niveau"), 0), (select NUM FROM IMPORTFFTA.FFTAARC where CODE="Arme"),@DATE_MODIF FROM IMPORTFFTA.RESULT_LICENCE;
COMMIT;

-- Nettoyage des tables
DELETE FROM Entite WHERE DATEMODIF <> @DATE_MODIF;
DELETE FROM Archers WHERE DATEMODIF <> @DATE_MODIF;

UPDATE ENTITE SET TYPEENTITE = 2 WHERE AGREMENTENTITE like '%000';
UPDATE ENTITE SET TYPEENTITE = 1 WHERE AGREMENTENTITE like '%00000';
UPDATE ENTITE SET TYPEENTITE = 0 WHERE AGREMENTENTITE like '0000000';

DROP SCHEMA IMPORTFFTA;

COMMIT;

SET LOG 1;