-- @author Aurélien JEOFFRAY
-- Optimise les performances sur les machines multi processeur/core ou Hyper-Threading
SET MULTI_THREADED 1;
SET LOG 0;

-- Integration des fichiers ASCII
CREATE TEMPORARY TABLE RESULT_CLUB AS SELECT * FROM CSVREAD('{temp}/result_club.TXT',null,null,STRINGDECODE('\t'));
MERGE INTO Entite (AGREMENTENTITE, NOMENTITE, VILLEENTITE, TYPEENTITE) 
    SELECT distinct "Agrément","Désignation","Localité",3
        from RESULT_CLUB
        where "Désignation" <> 'DEPARTEMENT FEDERATION';

CREATE TEMPORARY TABLE RESULT_LICENCE AS SELECT * FROM CSVREAD('{temp}/result_licence.TXT',null,null,STRINGDECODE('\t'));
CREATE TEMPORARY TABLE FFTACATEGORIE (NUM INTEGER PRIMARY KEY, CODE VARCHAR(2));
INSERT INTO FFTACATEGORIE VALUES (0,'P'), (1,'B'), (2,'M'), (3,'C'), (4,'J'), (5,'S'), (6,'V'), (7,'SV');
CREATE TEMPORARY TABLE FFTAARC (NUM INTEGER PRIMARY KEY, CODE VARCHAR(2));
INSERT INTO FFTAARC VALUES (0,'CL'), (1,'CO'), (2,'AD'), (3,'AC'), (4,'BB'), (5,'TL');
CREATE TEMPORARY TABLE FFTANIVEAU (NUM INTEGER PRIMARY KEY, CODE VARCHAR(2));
INSERT INTO FFTANIVEAU VALUES (0,'0'), (1,'1'), (2,'2'), (3,'3'), (4,'P'), (5,'Z');
MERGE INTO Archers (NUMLICENCEARCHER, NOMARCHER, PRENOMARCHER, 
    CERTIFMEDICAL, AGREMENTENTITE, GENREFFTA, CATEGORIEFFTA, NIVEAUFFTA,
    ARCFFTA) SELECT "N° Adh", "Nom", "Prénom", 
        "Certificat", "Agrément", CASEWHEN("Sexe"='H', 0, 1), 
        (select NUM FROM FFTACATEGORIE where CODE="Catégorie"),
        IFNULL((select NUM FROM FFTANIVEAU where CODE="Niveau"), 0), (select NUM FROM FFTAARC where CODE="Arme") FROM RESULT_LICENCE;
COMMIT;

-- Nettoyage des tables
DELETE FROM Entite WHERE AGREMENTENTITE IN (SELECT Entite.AGREMENTENTITE FROM Entite LEFT JOIN RESULT_CLUB ON Entite.AGREMENTENTITE="Agrément" WHERE "Agrément" IS NULL);
DELETE FROM Archers WHERE NUMLICENCEARCHER IN (SELECT Archers.NUMLICENCEARCHER FROM Archers LEFT JOIN RESULT_LICENCE ON Archers.NUMLICENCEARCHER="N° Adh" WHERE "N° Adh" IS NULL);

UPDATE ENTITE SET TYPEENTITE = 2 WHERE AGREMENTENTITE like '%000';
UPDATE ENTITE SET TYPEENTITE = 1 WHERE AGREMENTENTITE like '%00000';
UPDATE ENTITE SET TYPEENTITE = 0 WHERE AGREMENTENTITE like '0000000';

COMMIT;

SET LOG 1;