-- @author Aurélien JEOFFRAY
-- @release 1
CREATE TABLE FEDERATION (
		NUMFEDERATION	INTEGER AUTO_INCREMENT NOT NULL,
		SIGLEFEDERATION	VARCHAR(32),
		NOMFEDERATION	VARCHAR(128),
		PRIMARY KEY (NUMFEDERATION)
	);
INSERT INTO FEDERATION VALUES (1, 'FITA', STRINGDECODE('F\u00e9d\u00e9ration International de Tir \u000e0 l''Arc'));
INSERT INTO FEDERATION VALUES (2, 'FFTA', STRINGDECODE('F\u00e9d\u00e9ration Fran\u00e7aise de Tir \u000e0 l''Arc'));

CREATE TABLE CATEGORIE_REGLEMENT (
		NUMCATEGORIE_REGLEMENT	INTEGER AUTO_INCREMENT NOT NULL,
		NOMCATEGORIE	VARCHAR(128),
		PRIMARY KEY (NUMCATEGORIE_REGLEMENT)
	);
INSERT INTO CATEGORIE_REGLEMENT VALUES (1, 'Jeunes');
INSERT INTO CATEGORIE_REGLEMENT VALUES (2, 'Salle');
INSERT INTO CATEGORIE_REGLEMENT VALUES (3, STRINGDECODE('Ext\u00e9rieur'));

ALTER TABLE REGLEMENT ADD NUMFEDERATION INTEGER NOT NULL DEFAULT 2;
ALTER TABLE REGLEMENT ADD NUMCATEGORIE_REGLEMENT INTEGER NOT NULL DEFAULT 1;
ALTER TABLE REGLEMENT ADD REMOVABLE BOOLEAN DEFAULT FALSE;
ALTER TABLE REGLEMENT ADD FOREIGN KEY (NUMFEDERATION) REFERENCES FEDERATION (NUMFEDERATION) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE REGLEMENT ADD FOREIGN KEY (NUMCATEGORIE_REGLEMENT) REFERENCES CATEGORIE_REGLEMENT (NUMCATEGORIE_REGLEMENT) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE SURCLASSEMENT (
		NUMCRITERIASET INTEGER NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		NUMCRITERIASET_SURCLASSE INTEGER NULL,
		PRIMARY KEY (NUMCRITERIASET, NUMREGLEMENT),
		FOREIGN KEY (NUMCRITERIASET) REFERENCES CRITERIASET (NUMCRITERIASET) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUMREGLEMENT) REFERENCES REGLEMENT (NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUMCRITERIASET_SURCLASSE) REFERENCES CRITERIASET (NUMCRITERIASET) ON UPDATE CASCADE ON DELETE CASCADE
	);