CREATE TABLE ANCRAGES_BLASONS (
		NUMBLASON INTEGER NOT NULL,
		EMPLACEMENT INTEGER NOT NULL,
		ANCRAGEX DOUBLE NOT NULL,
		ANCRAGEY DOUBLE NOT NULL,
		PRIMARY KEY (NUMBLASON, EMPLACEMENT),
		FOREIGN KEY (NUMBLASON) REFERENCES BLASONS (NUMBLASON) ON UPDATE CASCADE ON DELETE CASCADE
	);
-- Emplacement:
-- 0 à 3 postion A, B, C, D
-- 4 les 4 à la fois, 5 AC, 6 AD
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 4, 0, 0 FROM BLASONS WHERE NOMBLASON NOT IN ('60cm', '40cm', 'Tri Spot "Vegas"', 'Tri Spot Vertical');

INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 5, 0, 0 FROM BLASONS WHERE NOMBLASON = '60cm';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 6, 0.5, 0 FROM BLASONS WHERE NOMBLASON = '60cm';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 0, 0, 0 FROM BLASONS WHERE NOMBLASON = '40cm';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 1, 0.5, 0 FROM BLASONS WHERE NOMBLASON = '40cm';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 2, 0, 0.5 FROM BLASONS WHERE NOMBLASON = '40cm';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 3, 0.5, 0.5 FROM BLASONS WHERE NOMBLASON = '40cm';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 0, 0, 0 FROM BLASONS WHERE NOMBLASON = 'Tri Spot "Vegas"';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 1, 0.5, 0 FROM BLASONS WHERE NOMBLASON = 'Tri Spot "Vegas"';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 2, 0, 0.5 FROM BLASONS WHERE NOMBLASON = 'Tri Spot "Vegas"';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 3, 0.5, 0.5 FROM BLASONS WHERE NOMBLASON = 'Tri Spot "Vegas"';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 0, 0, 0 FROM BLASONS WHERE NOMBLASON = 'Tri Spot Vertical';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 1, 0.5, 0 FROM BLASONS WHERE NOMBLASON = 'Tri Spot Vertical';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 2, 0.25, 0 FROM BLASONS WHERE NOMBLASON = 'Tri Spot Vertical';
INSERT INTO ANCRAGES_BLASONS (NUMBLASON, EMPLACEMENT, ANCRAGEX, ANCRAGEY) SELECT NUMBLASON, 3, 0.75, 0 FROM BLASONS WHERE NOMBLASON = 'Tri Spot Vertical';