#!/bin/sh
groupadd -f arccompetition

chmod +s /var/lib/ArcCompetition
chmod -R a+Xrw /var/lib/ArcCompetition
if [ -x /usr/bin/gksu ] ; then
	echo "gksu /usr/sbin/arccompetition-applyupdate \$1 \$2" > /usr/bin/arccompetition-applyupdate
else if [ -x /usr/bin/kdesu ] ; then
	echo "kdesu /usr/sbin/arccompetition-applyupdate \$1 \$2" > /usr/bin/arccompetition-applyupdate
fi
fi

chmod 700 /usr/sbin/arccompetition-applyupdate
