
package org.concoursjeunes.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PluginsWebServiceService", targetNamespace = "http://webservices.concoursjeunes.org/", wsdlLocation = "http://webservices.concoursjeunes.org/PluginsService.wsdl")
public class PluginsWebServiceService
    extends Service
{

    private final static URL PLUGINSWEBSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://webservices.concoursjeunes.org/PluginsService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PLUGINSWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public PluginsWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PluginsWebServiceService() {
        super(PLUGINSWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservices.concoursjeunes.org/", "PluginsWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns PluginsWebService
     */
    @WebEndpoint(name = "PluginsWebServicePort")
    public PluginsWebService getPluginsWebServicePort() {
        return (PluginsWebService)super.getPort(new QName("http://webservices.concoursjeunes.org/", "PluginsWebServicePort"), PluginsWebService.class);
    }

}
