CREATE TABLE CRITERE (
		CODECRITERE VARCHAR(16) NOT NULL,
		PROFILCRITERE VARCHAR(16) NOT NULL,
		LIBELLECRITERE VARCHAR(32),
		SORTORDERCRITERE INTEGER,
		CLASSEMENT BIGINT,
		PLACEMENT BIGINT,
		CODEFFTA VARCHAR(3)
	);

CREATE TABLE ENTITE (
		AGREMENTENTITE VARCHAR(7) NOT NULL,
		NOMENTITE VARCHAR(64),
		ADRESSEENTITE BIGINT,
		CODEPOSTALENTITE VARCHAR(5),
		VILLEENTITE VARCHAR(64),
		NOTEENTITE BIGINT,
		TYPEENTITE INTEGER
	);

CREATE TABLE ARCHERSFFTA (
		NUMLICENCEARCHER VARCHAR(64) NOT NULL,
		NOMARCHER VARCHAR(64),
		PRENOMARCHER VARCHAR(64),
		ALIASARCHER VARCHAR(128),
		CLUBARCHER VARCHAR(64),
		ARCARCHER INTEGER,
		CATEGORIEARCHER INTEGER,
		GENREARCHER INTEGER,
		NIVEAUARCHER CHAR(1),
		LIBELLENIVEAU VARCHAR(1),
		LIBELLECATEGORIE VARCHAR(8),
		AGREMENTCLUBARCHER VARCHAR(7),
		DATENAISS VARCHAR(8),
		CERTIFMEDICAL INTEGER,
		INC2 INTEGER
	);

CREATE TABLE DISTINGUER (
		NUMLICENCEARCHER VARCHAR(7) NOT NULL,
		CODECRITEREELEMENT VARCHAR(16) NOT NULL,
		CODECRITERE VARCHAR(16) NOT NULL,
		PROFILCRITERE VARCHAR(16) NOT NULL
	);

CREATE TABLE ENTITEFFTA (
		NUMENTITE INTEGER NOT NULL,
		AGREMENTENTITE VARCHAR(7),
		NOMENTITE VARCHAR(64),
		VILLEENTITE VARCHAR(64),
		LIGUEENTITE VARCHAR(2),
		CDENTITE VARCHAR(9)
	);

CREATE TABLE CRITEREELEMENT (
		CODECRITEREELEMENT VARCHAR(16) NOT NULL,
		CODECRITERE VARCHAR(16) NOT NULL,
		PROFILCRITERE VARCHAR(16) NOT NULL,
		LIBELLECRITEREELEMENT VARCHAR(32),
		ACTIF BIGINT
	);

CREATE TABLE ARCHERS (
		NUMLICENCEARCHER VARCHAR(7) NOT NULL,
		NOMARCHER VARCHAR(64),
		PRENOMARCHER VARCHAR(64),
		CERTIFMEDICAL BIGINT,
		AGREMENTENTITE VARCHAR(7),
		GENREFFTA INTEGER,
		CATEGORIEFFTA INTEGER,
		NIVEAUFFTA INTEGER,
		ARCFFTA INTEGER
	);

CREATE INDEX I_NOM_ARCHERS ON ARCHERS (NOMARCHER ASC);

ALTER TABLE DISTINGUER ADD CONSTRAINT SYS_IDX_58 PRIMARY KEY (NUMLICENCEARCHER, CODECRITEREELEMENT, CODECRITERE, PROFILCRITERE);

ALTER TABLE CRITERE ADD CONSTRAINT SYS_IDX_54 PRIMARY KEY (CODECRITERE, PROFILCRITERE);

ALTER TABLE ENTITEFFTA ADD CONSTRAINT SYS_IDX_46 PRIMARY KEY (NUMENTITE);

ALTER TABLE ARCHERS ADD CONSTRAINT SYS_IDX_50 PRIMARY KEY (NUMLICENCEARCHER);

ALTER TABLE CRITEREELEMENT ADD CONSTRAINT SYS_IDX_56 PRIMARY KEY (CODECRITEREELEMENT, CODECRITERE, PROFILCRITERE);

ALTER TABLE ENTITE ADD CONSTRAINT SYS_IDX_48 PRIMARY KEY (AGREMENTENTITE);

ALTER TABLE ARCHERSFFTA ADD CONSTRAINT SYS_IDX_52 PRIMARY KEY (NUMLICENCEARCHER);

