SET AUTOCOMMIT OFF;
SET MULTI_THREADED 1;

DROP TABLE ARCHERSFFTA;
DROP TABLE ENTITEFFTA;

CREATE TABLE IF NOT EXISTS LIBELLE (
		ID_LIBELLE UUID NOT NULL DEFAULT RANDOM_UUID(),
		LANG VARCHAR(5),
		LIBELLE VARCHAR(255),
		PRIMARY KEY (ID_LIBELLE, LANG)
	);

CREATE TABLE IF NOT EXISTS CIVILITY (
		ID_CIVILITY UUID NOT NULL DEFAULT RANDOM_UUID(),
		ABREVIATION VARCHAR(10),
		LIBELLE VARCHAR(64),
		PRIMARY KEY (ID_CIVILITY)
	);
INSERT INTO CIVILITY (ABREVIATION,LIBELLE) VALUES ('M.', 'Monsieur');
INSERT INTO CIVILITY (ABREVIATION,LIBELLE) VALUES ('Mme', 'Madame');
INSERT INTO CIVILITY (ABREVIATION,LIBELLE) VALUES ('Mlle', 'Mademoiselle');
INSERT INTO CIVILITY (ABREVIATION,LIBELLE) VALUES ('Dr.', 'Docteur');
INSERT INTO CIVILITY (ABREVIATION,LIBELLE) VALUES ('Me', 'Maître');

CREATE TABLE IF NOT EXISTS CONTACT (
		ID_CONTACT UUID NOT NULL DEFAULT RANDOM_UUID(),
		NAME VARCHAR(128),
		FIRSTNAME VARCHAR(128),
		ID_CIVILITY UUID,
		ADDRESS VARCHAR(255),
		ZIP_CODE VARCHAR(10),
		CITY VARCHAR(64),
		NOTE TEXT,
		PRIMARY KEY (ID_CONTACT),
		FOREIGN KEY (ID_CIVILITY) REFERENCES CIVILITY (ID_CIVILITY) ON UPDATE CASCADE ON DELETE CASCADE
	);
CREATE INDEX IF NOT EXISTS I_NAME ON CONTACT (NAME ASC);
CREATE INDEX IF NOT EXISTS I_FIRSTNAME ON CONTACT (FIRSTNAME ASC);

CREATE TABLE IF NOT EXISTS COORDINATE (
		ID_COORDINATE UUID NOT NULL DEFAULT RANDOM_UUID(),
		ID_CONTACT UUID NOT NULL,
		CODE_COORDINATE_TYPE VARCHAR(10),
		"VALUE" VARCHAR(64),
		PRIMARY KEY (ID_COORDINATE),
		FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT (ID_CONTACT) ON UPDATE CASCADE ON DELETE CASCADE
	);
	

CREATE TABLE IF NOT EXISTS CATEGORIE_CONTACT (
		NUM_CATEGORIE_CONTACT INTEGER AUTO_INCREMENT NOT NULL,
		ID_LIBELLE UUID NOT NULL,
		PRIMARY KEY (NUM_CATEGORIE_CONTACT)
	);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Archer(e)');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Bowman');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (1,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Président(e)');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','President');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (2,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Secrétaire');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Secretary');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (3,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Trésorier(e)');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Treasurer');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (4,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Résponsable Inscription');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Registration Manager');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (5,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Divers');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Diverse');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (6,@NEW_UUID);


CREATE TABLE IF NOT EXISTS ASSOCIER_CATEGORIE_CONTACT (
		ID_CONTACT UUID NOT NULL,
		NUM_CATEGORIE_CONTACT INTEGER NOT NULL,
		PRIMARY KEY (ID_CONTACT, NUM_CATEGORIE_CONTACT),
		FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT (ID_CONTACT) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUM_CATEGORIE_CONTACT) REFERENCES CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT) ON UPDATE CASCADE ON DELETE CASCADE
	);
	
ALTER TABLE ENTITE ADD ID_ENTITE UUID NOT NULL DEFAULT RANDOM_UUID() BEFORE AGREMENTENTITE;
ALTER TABLE ENTITE ADD REMOVABLE BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE ENTITE ALTER COLUMN AGREMENTENTITE VARCHAR(32);
CREATE INDEX IF NOT EXISTS I_AGREMENT_ENTITE ON ENTITE (AGREMENTENTITE ASC);

-- on modifie la structure des tables
ALTER TABLE PARAM ADD DEFAULT_LANG VARCHAR(5) NOT NULL;
UPDATE PARAM SET DEFAULT_LANG = 'fr';
ALTER TABLE ARCHERS ADD ID_CONTACT UUID NOT NULL DEFAULT RANDOM_UUID() BEFORE NUMLICENCEARCHER;
ALTER TABLE ARCHERS ALTER COLUMN NUMLICENCEARCHER VARCHAR(32);
ALTER TABLE ARCHERS ADD ID_ENTITE UUID NULL BEFORE AGREMENTENTITE;
CREATE INDEX IF NOT EXISTS I_NUMLICENCEARCHER ON ARCHERS (NUMLICENCEARCHER ASC);

-- On remplit la table des contacts
INSERT INTO CONTACT (ID_CONTACT,NAME,FIRSTNAME) SELECT ID_CONTACT,NOMARCHER,PRENOMARCHER FROM ARCHERS;
UPDATE ARCHERS SET ID_ENTITE = (SELECT ID_ENTITE FROM ENTITE WHERE ENTITE.AGREMENTENTITE=ARCHERS.AGREMENTENTITE);

-- on regénére la table de liaison
CREATE LOCAL TEMPORARY TABLE TEMP_DISTINGUER AS SELECT * FROM DISTINGUER;

DROP TABLE DISTINGUER;
CREATE TABLE DISTINGUER (
		ID_CONTACT UUID NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		NUMCRITERIASET INTEGER NOT NULL,
		PRIMARY KEY (ID_CONTACT, NUMREGLEMENT, NUMCRITERIASET),
		FOREIGN KEY (NUMREGLEMENT) REFERENCES REGLEMENT (NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUMCRITERIASET) REFERENCES CRITERIASET (NUMCRITERIASET) ON UPDATE CASCADE ON DELETE CASCADE
	);
INSERT INTO DISTINGUER (ID_CONTACT, NUMREGLEMENT, NUMCRITERIASET) SELECT ID_CONTACT,NUMREGLEMENT,NUMCRITERIASET FROM TEMP_DISTINGUER D INNER JOIN ARCHERS A ON A.NUMLICENCEARCHER=D.NUMLICENCEARCHER;
DROP TABLE TEMP_DISTINGUER;

-- On refait les liens et index et purge les données obsolete
DROP INDEX IF EXISTS I_NOM_ARCHER;
DROP INDEX IF EXISTS I_PRENOM_ARCHER;
ALTER TABLE ARCHERS DROP COLUMN NOMARCHER;
ALTER TABLE ARCHERS DROP COLUMN PRENOMARCHER;
ALTER TABLE ARCHERS DROP COLUMN AGREMENTENTITE;
ALTER TABLE ENTITE DROP PRIMARY KEY;
ALTER TABLE ENTITE ADD PRIMARY KEY (ID_ENTITE);
ALTER TABLE ARCHERS DROP PRIMARY KEY;
ALTER TABLE ARCHERS ADD PRIMARY KEY (ID_CONTACT);
ALTER TABLE ARCHERS ADD FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT (ID_CONTACT) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ARCHERS ADD FOREIGN KEY (ID_ENTITE) REFERENCES ENTITE (ID_ENTITE) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE DISTINGUER ADD FOREIGN KEY (ID_CONTACT) REFERENCES ARCHERS (ID_CONTACT) ON UPDATE CASCADE ON DELETE CASCADE;

INSERT INTO ASSOCIER_CATEGORIE_CONTACT (ID_CONTACT, NUM_CATEGORIE_CONTACT) SELECT ID_CONTACT, 1 FROM CONTACT;

COMMIT;
SET AUTOCOMMIT ON;