-- @release 1

TRUNCATE TABLE EntiteFFTA;
INSERT INTO EntiteFFTA SELECT distinct NUM,AGR,NOM,
	VILLE,LIGUE,CD from CSVREAD('ressources/update/FICLUB.TXT','NUM;AGR;NOM;VILLE;LIGUE;CD;INC1;INC2;INC3;INC4',null,';');

MERGE INTO Entite (AGREMENTENTITE, NOMENTITE, VILLEENTITE, TYPEENTITE) 
	SELECT AGREMENTENTITE, NOMENTITE, VILLEENTITE, 3 FROM EntiteFFTA
		WHERE NomEntite <> 'DEPARTEMENT FEDERATION';

DELETE FROM Entite WHERE AGREMENTENTITE IN (SELECT Entite.AGREMENTENTITE FROM Entite LEFT JOIN EntiteFFTA ON Entite.AGREMENTENTITE=EntiteFFTA.AGREMENTENTITE WHERE EntiteFFTA.AGREMENTENTITE IS NULL);

TRUNCATE TABLE EntiteFFTA;

UPDATE ENTITE SET TYPEENTITE = 2 WHERE AGREMENTENTITE like '%000';
UPDATE ENTITE SET TYPEENTITE = 1 WHERE like '%00000';
UPDATE ENTITE SET TYPEENTITE = 0 WHERE like '0000000';