-- Création de la base de données de ConcoursJeunes
-- @author Aurélien JEOFFRAY
-- @release 1
CREATE TABLE PARAM (
		DBVERSION INTEGER NOT NULL,
		APPREVISION INTEGER NOT NULL
	);
INSERT INTO PARAM (DBVERSION, APPREVISION) VALUES (1, 1);

CREATE TABLE REGLEMENT (
		NUMREGLEMENT INTEGER AUTO_INCREMENT NOT NULL,
		NOMREGLEMENT VARCHAR(32),
		NBSERIE INTEGER,
		NBVOLEEPARSERIE INTEGER,
		NBFLECHEPARVOLEE INTEGER,
		NBMEMBRESEQUIPE INTEGER,
		NBMEMBRESRETENU INTEGER,
		ISOFFICIAL BOOLEAN,
		PRIMARY KEY (NUMREGLEMENT)
	);
CREATE INDEX I_NOM_REGLEMENT ON REGLEMENT (NOMREGLEMENT ASC);
	
CREATE TABLE CRITERE (
		CODECRITERE VARCHAR(16) NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		LIBELLECRITERE VARCHAR(32),
		SORTORDERCRITERE INTEGER,
		CLASSEMENT BOOLEAN,
		CLASSEMENTEQUIPE BOOLEAN DEFAULT FALSE,
		PLACEMENT BOOLEAN,
		CODEFFTA VARCHAR(16),
		PRIMARY KEY (CODECRITERE, NUMREGLEMENT),
		FOREIGN KEY (NUMREGLEMENT) REFERENCES REGLEMENT (NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE
	);

CREATE TABLE CRITEREELEMENT (
		CODECRITEREELEMENT VARCHAR(16) NOT NULL,
		CODECRITERE VARCHAR(16) NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		LIBELLECRITEREELEMENT VARCHAR(32),
		ACTIF BOOLEAN,
		PRIMARY KEY (CODECRITEREELEMENT, CODECRITERE, NUMREGLEMENT),
		FOREIGN KEY (CODECRITERE, NUMREGLEMENT) REFERENCES CRITERE (CODECRITERE, NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE
	);

CREATE TABLE BLASONS (
		NUMBLASON INTEGER AUTO_INCREMENT NOT NULL,
		NOMBLASON VARCHAR(32) NOT NULL,
		HORIZONTAL_RATIO DOUBLE NOT NULL,
		VERTICAL_RATIO DOUBLE NOT NULL,
		NBARCHER INTEGER NOT NULL,
		NUMORDRE INTEGER NOT NULL,
		PRIMARY KEY (NUMBLASON)
	);
INSERT INTO BLASONS VALUES (1, '122cm', 1, 1, 4, 122);
INSERT INTO BLASONS VALUES (2, '80cm', 1, 1, 4, 80);
INSERT INTO BLASONS VALUES (3, '60cm', 0.5, 1, 2, 60);
INSERT INTO BLASONS VALUES (4, '40cm', 0.5, 0.5, 1, 40);
INSERT INTO BLASONS VALUES (5, 'Tri Spot "Vegas"', 0.5, 0.5, 1, 39);
INSERT INTO BLASONS VALUES (6, 'Tri Spot Vertical', 0.25, 1, 1, 24);

CREATE TABLE DISTANCESBLASONS (
		NUMDISTANCESBLASONS INTEGER AUTO_INCREMENT NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		BLASONS INTEGER,
		NUMBLASON INTEGER NOT NULL,
		FOREIGN KEY (NUMREGLEMENT) REFERENCES REGLEMENT (NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUMBLASON) REFERENCES BLASONS (NUMBLASON) ON UPDATE CASCADE ON DELETE CASCADE
	);
ALTER TABLE DISTANCESBLASONS DROP PRIMARY KEY;
CREATE PRIMARY KEY ON DISTANCESBLASONS (NUMDISTANCESBLASONS, NUMREGLEMENT);

CREATE TABLE DISTANCES (
		NUMDISTANCES INTEGER AUTO_INCREMENT NOT NULL,
		NUMDISTANCESBLASONS INTEGER NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		DISTANCE INTEGER,
		FOREIGN KEY (NUMDISTANCESBLASONS, NUMREGLEMENT) REFERENCES DISTANCESBLASONS (NUMDISTANCESBLASONS, NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE
	);

ALTER TABLE DISTANCES DROP PRIMARY KEY;
CREATE PRIMARY KEY ON DISTANCES (NUMDISTANCES, NUMDISTANCESBLASONS, NUMREGLEMENT);

CREATE TABLE CRITERIASET (
		NUMCRITERIASET INTEGER NOT NULL,
		PRIMARY KEY (NUMCRITERIASET)
	);

CREATE TABLE POSSEDE (
		NUMCRITERIASET INTEGER NOT NULL,
		CODECRITEREELEMENT VARCHAR(16) NOT NULL,
		CODECRITERE VARCHAR(16) NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		PRIMARY KEY (NUMCRITERIASET, CODECRITEREELEMENT, CODECRITERE, NUMREGLEMENT),
		FOREIGN KEY (NUMCRITERIASET) REFERENCES CRITERIASET (NUMCRITERIASET) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (CODECRITEREELEMENT, CODECRITERE, NUMREGLEMENT) REFERENCES CRITEREELEMENT (CODECRITEREELEMENT, CODECRITERE, NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE
	);

CREATE TABLE ARCHERSFFTA (
		NUMLICENCEARCHER VARCHAR(64) NOT NULL,
		NOMARCHER VARCHAR(64),
		PRENOMARCHER VARCHAR(64),
		ALIASARCHER VARCHAR(128),
		CLUBARCHER VARCHAR(64),
		ARCARCHER INTEGER,
		CATEGORIEARCHER INTEGER,
		GENREARCHER INTEGER,
		NIVEAUARCHER CHAR(1),
		LIBELLENIVEAU VARCHAR(1),
		LIBELLECATEGORIE VARCHAR(8),
		AGREMENTCLUBARCHER VARCHAR(7),
		DATENAISS VARCHAR(8),
		CERTIFMEDICAL BOOLEAN,
		INC2 INTEGER,
		PRIMARY KEY (NUMLICENCEARCHER)
	);

CREATE TABLE ENTITEFFTA (
		NUMENTITE INTEGER NOT NULL,
		AGREMENTENTITE VARCHAR(7),
		NOMENTITE VARCHAR(64),
		VILLEENTITE VARCHAR(64),
		LIGUEENTITE VARCHAR(2),
		CDENTITE VARCHAR(9),
		PRIMARY KEY (NUMENTITE)
	);

CREATE TABLE ARCHERS (
		NUMLICENCEARCHER VARCHAR(7) NOT NULL,
		NOMARCHER VARCHAR(64),
		PRENOMARCHER VARCHAR(64),
		CERTIFMEDICAL BOOLEAN,
		AGREMENTENTITE VARCHAR(7),
		GENREFFTA INTEGER,
		CATEGORIEFFTA INTEGER,
		NIVEAUFFTA INTEGER,
		ARCFFTA INTEGER,
		PRIMARY KEY (NUMLICENCEARCHER)
	);

CREATE INDEX I_NOM_ARCHERS ON ARCHERS (NOMARCHER ASC);
CREATE INDEX I_PRENOM_ARCHERS ON ARCHERS (PRENOMARCHER ASC);

CREATE TABLE ENTITE (
		AGREMENTENTITE VARCHAR(7) NOT NULL,
		NOMENTITE VARCHAR(64),
		ADRESSEENTITE CLOB,
		CODEPOSTALENTITE VARCHAR(5),
		VILLEENTITE VARCHAR(64),
		NOTEENTITE CLOB,
		TYPEENTITE INTEGER,
		PRIMARY KEY (AGREMENTENTITE)
	);

CREATE TABLE ASSOCIER (
		NUMDISTANCESBLASONS INTEGER NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		NUMCRITERIASET INTEGER NOT NULL,
		PRIMARY KEY (NUMDISTANCESBLASONS, NUMREGLEMENT, NUMCRITERIASET),
		FOREIGN KEY (NUMDISTANCESBLASONS, NUMREGLEMENT) REFERENCES DISTANCESBLASONS (NUMDISTANCESBLASONS, NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUMCRITERIASET) REFERENCES CRITERIASET (NUMCRITERIASET) ON UPDATE CASCADE ON DELETE CASCADE
	);
	
CREATE TABLE DISTINGUER (
		NUMLICENCEARCHER VARCHAR(7) NOT NULL,
		NUMREGLEMENT INTEGER NOT NULL,
		NUMCRITERIASET INTEGER NOT NULL,
		PRIMARY KEY (NUMLICENCEARCHER, NUMREGLEMENT, NUMCRITERIASET),
		FOREIGN KEY (NUMLICENCEARCHER) REFERENCES ARCHERS (NUMLICENCEARCHER) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUMREGLEMENT) REFERENCES REGLEMENT (NUMREGLEMENT) ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (NUMCRITERIASET) REFERENCES CRITERIASET (NUMCRITERIASET) ON UPDATE CASCADE ON DELETE CASCADE
	);
