-- @release 1

TRUNCATE TABLE EntiteFFTA;
INSERT INTO EntiteFFTA SELECT distinct NUM,AGR,NOM,
	VILLE,LIGUE,CD from CSVREAD('ressources/update/FICLUB.TXT','NUM;AGR;NOM;VILLE;LIGUE;CD;INC1;INC2;INC3;INC4',null,';');

MERGE INTO Entite (AGREMENTENTITE, NOMENTITE, VILLEENTITE) 
	SELECT AGREMENTENTITE, NOMENTITE, VILLEENTITE FROM EntiteFFTA
		WHERE NomEntite <> 'DEPARTEMENT FEDERATION';

DELETE FROM Entite WHERE AGREMENTENTITE IN (SELECT Entite.AGREMENTENTITE FROM Entite LEFT JOIN EntiteFFTA ON Entite.AGREMENTENTITE=EntiteFFTA.AGREMENTENTITE WHERE EntiteFFTA.AGREMENTENTITE IS NULL);

TRUNCATE TABLE EntiteFFTA;